version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./orders.db
      - FRONTEND_URLS=*
    volumes:
      - ./backend/orders.db:/app/orders.db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE=http://localhost:8000
    depends_on:
      - backend
